/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Controller.ControllerHomeUser;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author maula
 */
public class HomeUser extends javax.swing.JFrame {
    private ControllerHomeUser ctrluser;
    /**
     * Creates new form HomeUser
     */
    public HomeUser() {
        initComponents();
        ctrluser = new ControllerHomeUser(this);
    }

    public JComboBox getDaerah(){
        return jComboBox3;
    }
    public JLabel getKabupaten(){
        return namaKabupaten;
    }
    public JTable getTabelha(){
        return jTable1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        bodyPanel = new javax.swing.JPanel();
        secondPanel = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel82 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        buttonKeluar1 = new javax.swing.JButton();
        namaKabupaten1 = new javax.swing.JLabel();
        kabupaten1 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        buttonBeranda = new javax.swing.JButton();
        buttonHarga = new javax.swing.JButton();
        buttonGrafik = new javax.swing.JButton();
        jLabel78 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        buttonProfil = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();
        namaKabupaten = new javax.swing.JLabel();
        kabupaten = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        daerah = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton19 = new javax.swing.JButton();
        beranda = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        harga = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        grafik = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Harga Hasil Pertanian");

        bodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        secondPanel.setLayout(new java.awt.CardLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(42, 255, 72));
        kGradientPanel2.setkGradientFocus(300);
        kGradientPanel2.setkStartColor(new java.awt.Color(11, 66, 8));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel82.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Sistem Informasi");
        kGradientPanel2.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 25, -1, -1));

        jLabel76.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Harga Hasil Pertanian");
        kGradientPanel2.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 53, -1, -1));

        jLabel80.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("____________  ___________");
        kGradientPanel2.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 76, 176, -1));

        jLabel83.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("V 1.0");
        kGradientPanel2.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 375, -1, -1));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonKeluar1.setBackground(new java.awt.Color(255, 0, 0));
        buttonKeluar1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        buttonKeluar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_logout_rounded_24px.png"))); // NOI18N
        buttonKeluar1.setText("Keluar");
        buttonKeluar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonKeluar1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonKeluar1MouseReleased(evt);
            }
        });
        buttonKeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluar1ActionPerformed(evt);
            }
        });
        jPanel9.add(buttonKeluar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 11, -1, -1));

        kGradientPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 315, -1, 54));

        namaKabupaten1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        namaKabupaten1.setForeground(new java.awt.Color(255, 255, 255));
        namaKabupaten1.setText("PETANI");
        kGradientPanel2.add(namaKabupaten1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, -1));

        kabupaten1.setFont(new java.awt.Font("Berlin Sans FB", 2, 18)); // NOI18N
        kabupaten1.setForeground(new java.awt.Color(255, 255, 255));
        kabupaten1.setText("Selamat Datang");
        kGradientPanel2.add(kabupaten1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, -1));

        secondPanel.add(kGradientPanel2, "card3");

        kGradientPanel1.setkEndColor(new java.awt.Color(42, 255, 72));
        kGradientPanel1.setkGradientFocus(300);
        kGradientPanel1.setkStartColor(new java.awt.Color(11, 66, 8));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel81.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Sistem Informasi");
        kGradientPanel1.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 25, -1, -1));

        jLabel74.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Harga Hasil Pertanian");
        kGradientPanel1.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 53, -1, -1));

        jLabel79.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("____________  ___________");
        kGradientPanel1.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 76, 176, -1));

        buttonBeranda.setBackground(new java.awt.Color(190, 190, 190));
        buttonBeranda.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        buttonBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_home_24px_1.png"))); // NOI18N
        buttonBeranda.setText("Beranda");
        buttonBeranda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBerandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonBerandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonBerandaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonBerandaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonBerandaMouseReleased(evt);
            }
        });
        buttonBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBerandaActionPerformed(evt);
            }
        });
        kGradientPanel1.add(buttonBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 180, -1));

        buttonHarga.setBackground(new java.awt.Color(190, 190, 190));
        buttonHarga.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        buttonHarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_us_dollar_24px.png"))); // NOI18N
        buttonHarga.setText("Harga Hasil Pertanian");
        buttonHarga.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonHarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHargaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonHargaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonHargaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonHargaMouseReleased(evt);
            }
        });
        buttonHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHargaActionPerformed(evt);
            }
        });
        kGradientPanel1.add(buttonHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, -1));

        buttonGrafik.setBackground(new java.awt.Color(190, 190, 190));
        buttonGrafik.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        buttonGrafik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_bullish_24px.png"))); // NOI18N
        buttonGrafik.setText("Grafik");
        buttonGrafik.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonGrafik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonGrafikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonGrafikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonGrafikMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonGrafikMouseReleased(evt);
            }
        });
        buttonGrafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGrafikActionPerformed(evt);
            }
        });
        kGradientPanel1.add(buttonGrafik, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, -1));

        jLabel78.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("V 1.0");
        kGradientPanel1.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 375, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonProfil.setBackground(new java.awt.Color(0, 0, 255));
        buttonProfil.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        buttonProfil.setForeground(new java.awt.Color(255, 255, 255));
        buttonProfil.setText("Ganti Daerah");
        buttonProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProfilActionPerformed(evt);
            }
        });
        jPanel8.add(buttonProfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 40));

        buttonKeluar.setBackground(new java.awt.Color(255, 0, 0));
        buttonKeluar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        buttonKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_logout_rounded_24px.png"))); // NOI18N
        buttonKeluar.setText("Keluar");
        buttonKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonKeluarMousePressed(evt);
            }
        });
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });
        jPanel8.add(buttonKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 11, -1, -1));

        kGradientPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 315, -1, 54));

        namaKabupaten.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        namaKabupaten.setForeground(new java.awt.Color(255, 255, 255));
        namaKabupaten.setText("JEMBER");
        kGradientPanel1.add(namaKabupaten, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, -1));

        kabupaten.setFont(new java.awt.Font("Berlin Sans FB", 2, 18)); // NOI18N
        kabupaten.setForeground(new java.awt.Color(255, 255, 255));
        kabupaten.setText("~ Kabupaten ~");
        kGradientPanel1.add(kabupaten, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 240, 120, -1));

        secondPanel.add(kGradientPanel1, "card2");

        bodyPanel.add(secondPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 400));

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));
        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel77.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel77.setText("Pilih Daerah Kabupaten/Kota");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Banyuwangi", "Bondowoso", "Jember", "Lumajang" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(0, 102, 0));
        jButton19.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("Pilih");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout daerahLayout = new javax.swing.GroupLayout(daerah);
        daerah.setLayout(daerahLayout);
        daerahLayout.setHorizontalGroup(
            daerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daerahLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(daerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(daerahLayout.createSequentialGroup()
                        .addComponent(jLabel77)
                        .addContainerGap(356, Short.MAX_VALUE))
                    .addGroup(daerahLayout.createSequentialGroup()
                        .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton19)
                        .addGap(61, 61, 61))))
        );
        daerahLayout.setVerticalGroup(
            daerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daerahLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel77)
                .addGap(32, 32, 32)
                .addGroup(daerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton19)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(295, Short.MAX_VALUE))
        );

        mainPanel.add(daerah, "card6");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Lihat Harga Tanaman");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Lihat Grafik");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Ganti Daerah");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel71.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel71.setText("Beranda");

        javax.swing.GroupLayout berandaLayout = new javax.swing.GroupLayout(beranda);
        beranda.setLayout(berandaLayout);
        berandaLayout.setHorizontalGroup(
            berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(berandaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel71)
                .addContainerGap(479, Short.MAX_VALUE))
            .addGroup(berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(berandaLayout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(44, 44, 44)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );
        berandaLayout.setVerticalGroup(
            berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(berandaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel71)
                .addContainerGap(353, Short.MAX_VALUE))
            .addGroup(berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(berandaLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addGroup(berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(182, Short.MAX_VALUE)))
        );

        mainPanel.add(beranda, "card2");

        jLabel72.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel72.setText("Harga Hasil Pertanian");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hasil Pertanian", "Jenis", "Harga (/kg) (Rp)", "Tanggal Diperbarui"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextField1.setText("Cari"); // NOI18N
        jTextField1.setName(""); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cari");

        javax.swing.GroupLayout hargaLayout = new javax.swing.GroupLayout(harga);
        harga.setLayout(hargaLayout);
        hargaLayout.setHorizontalGroup(
            hargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hargaLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel72)
                .addContainerGap(391, Short.MAX_VALUE))
            .addGroup(hargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hargaLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addGroup(hargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hargaLayout.createSequentialGroup()
                            .addComponent(jTextField1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(60, Short.MAX_VALUE)))
        );
        hargaLayout.setVerticalGroup(
            hargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hargaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel72)
                .addContainerGap(356, Short.MAX_VALUE))
            .addGroup(hargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hargaLayout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addGroup(hargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        jTextField1.getAccessibleContext().setAccessibleName("");

        mainPanel.add(harga, "card4");

        jLabel75.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel75.setText("Grafik Hasil Pertanian");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Hasil Pertanian --", "Padi", "Jagung", "Tebu", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(0, 102, 0));
        jButton15.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Pilih");

        javax.swing.GroupLayout grafikLayout = new javax.swing.GroupLayout(grafik);
        grafik.setLayout(grafikLayout);
        grafikLayout.setHorizontalGroup(
            grafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grafikLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(grafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel75)
                    .addGroup(grafikLayout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton15)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        grafikLayout.setVerticalGroup(
            grafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grafikLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel75)
                .addGap(26, 26, 26)
                .addGroup(grafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(301, Short.MAX_VALUE))
        );

        mainPanel.add(grafik, "card5");

        bodyPanel.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 400));

        jDesktopPane1.setLayer(bodyPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBerandaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBerandaMouseClicked

    private void buttonBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBerandaMouseEntered
        // TODO add your handling code here:
        buttonBeranda.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_buttonBerandaMouseEntered

    private void buttonBerandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBerandaMouseExited
        // TODO add your handling code here:
        buttonBeranda.setBackground(new Color(190,190,190));
    }//GEN-LAST:event_buttonBerandaMouseExited

    private void buttonBerandaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBerandaMousePressed
        // TODO add your handling code here:
        buttonBeranda.setBackground(new Color(190,190,190));
    }//GEN-LAST:event_buttonBerandaMousePressed

    private void buttonBerandaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBerandaMouseReleased
        // TODO add your handling code here:
        buttonBeranda.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_buttonBerandaMouseReleased

    private void buttonBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBerandaActionPerformed
        // TODO add your handling code here:
        // hapus
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // isikan
        mainPanel.add(beranda);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_buttonBerandaActionPerformed

    private void buttonHargaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHargaMouseEntered
        // TODO add your handling code here:
        buttonHarga.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_buttonHargaMouseEntered

    private void buttonHargaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHargaMouseExited
        // TODO add your handling code here:
        buttonHarga.setBackground(new Color(190,190,190));
    }//GEN-LAST:event_buttonHargaMouseExited

    private void buttonHargaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHargaMousePressed
        // TODO add your handling code here:
        buttonHarga.setBackground(new Color(190,190,190));
    }//GEN-LAST:event_buttonHargaMousePressed

    private void buttonHargaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHargaMouseReleased
        // TODO add your handling code here:
        buttonHarga.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_buttonHargaMouseReleased

    private void buttonHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHargaActionPerformed
        // TODO add your handling code here:
        // hapus
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // isikan
        mainPanel.add(harga);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_buttonHargaActionPerformed

    private void buttonGrafikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGrafikMouseEntered
        // TODO add your handling code here:
        buttonGrafik.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_buttonGrafikMouseEntered

    private void buttonGrafikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGrafikMouseExited
        // TODO add your handling code here:
        buttonGrafik.setBackground(new Color(190,190,190));
    }//GEN-LAST:event_buttonGrafikMouseExited

    private void buttonGrafikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGrafikMousePressed
        // TODO add your handling code here:
        buttonGrafik.setBackground(new Color(190,190,190));
    }//GEN-LAST:event_buttonGrafikMousePressed

    private void buttonGrafikMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGrafikMouseReleased
        // TODO add your handling code here:
        buttonGrafik.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_buttonGrafikMouseReleased

    private void buttonGrafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGrafikActionPerformed
        // TODO add your handling code here:
        // hapus
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // isikan
        mainPanel.add(grafik);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_buttonGrafikActionPerformed

    private void buttonProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProfilActionPerformed
        // TODO add your handling code here:
        // hapus
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        secondPanel.removeAll();
        secondPanel.repaint();
        secondPanel.revalidate();

        // isikan
        mainPanel.add(daerah);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        secondPanel.add(kGradientPanel2);
        secondPanel.repaint();
        secondPanel.revalidate();
    }//GEN-LAST:event_buttonProfilActionPerformed

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this,"Anda Yakin Ingin Keluar?","Keluar",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if (jawab==JOptionPane.YES_OPTION) {
                this.setVisible(false);
                new Login().setVisible(true);
        }
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        // hapus
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        secondPanel.removeAll();
        secondPanel.repaint();
        secondPanel.revalidate();

        // isikan
        mainPanel.add(beranda);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        secondPanel.add(kGradientPanel1);
        secondPanel.repaint();
        secondPanel.revalidate();
        
        kabupaten.setText("~ Kabupaten ~");
        namaKabupaten.setText(ctrluser.getKabupaten());
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        // hapus
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // isikan
        mainPanel.add(harga);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
        // hapus
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // isikan
        mainPanel.add(grafik);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        // hapus
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // isikan
        mainPanel.add(daerah);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void buttonKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluar1ActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this,"Anda Yakin Ingin Keluar?","Keluar",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if (jawab==JOptionPane.YES_OPTION) {
                this.setVisible(false);
                new Login().setVisible(true);
            
        }
    }//GEN-LAST:event_buttonKeluar1ActionPerformed

    private void buttonKeluar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonKeluar1MousePressed
        // TODO add your handling code here:
        buttonKeluar1.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_buttonKeluar1MousePressed

    private void buttonKeluar1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonKeluar1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonKeluar1MouseReleased

    private void buttonKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonKeluarMousePressed
        // TODO add your handling code here:
        buttonKeluar.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_buttonKeluarMousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel beranda;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton buttonBeranda;
    private javax.swing.JButton buttonGrafik;
    private javax.swing.JButton buttonHarga;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonKeluar1;
    private javax.swing.JButton buttonProfil;
    private javax.swing.JPanel daerah;
    private javax.swing.JPanel grafik;
    private javax.swing.JPanel harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton19;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel kabupaten;
    private javax.swing.JLabel kabupaten1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaKabupaten;
    private javax.swing.JLabel namaKabupaten1;
    private javax.swing.JPanel secondPanel;
    // End of variables declaration//GEN-END:variables
}
