/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Controller.ControllerLogin;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author maula
 */
public class Login extends javax.swing.JFrame {
    
    private ControllerLogin ctrllgn;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        ctrllgn = new ControllerLogin(this);
    }

    public JTextField getUsername(){
        return isiusername;
    }
    public JTextField getPassword(){
        return isipassword;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        selamatdatang = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        signin = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        isiusername = new javax.swing.JTextField();
        kliksignin = new javax.swing.JButton();
        lupapassword = new javax.swing.JLabel();
        isipassword = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        kliksignin1 = new javax.swing.JButton();
        lupapassword1 = new javax.swing.JLabel();
        si1 = new javax.swing.JLabel();
        si2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Harga Hasil Pertanian");

        kGradientPanel2.setkEndColor(new java.awt.Color(42, 255, 72));
        kGradientPanel2.setkGradientFocus(300);
        kGradientPanel2.setkStartColor(new java.awt.Color(11, 66, 8));

        selamatdatang.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        selamatdatang.setForeground(new java.awt.Color(255, 255, 255));
        selamatdatang.setText("Selamat Datang di");

        label1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Semua harga hasil pertanian di Indonesia");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        signin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        signin.setText("Masuk");

        username.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        username.setText("Nama Pengguna");

        password.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        password.setText("Password");

        isiusername.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        isiusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiusernameActionPerformed(evt);
            }
        });
        isiusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiusernameKeyTyped(evt);
            }
        });

        kliksignin.setBackground(new java.awt.Color(0, 102, 0));
        kliksignin.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        kliksignin.setForeground(new java.awt.Color(255, 255, 255));
        kliksignin.setText("Masuk");
        kliksignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kliksigninMousePressed(evt);
            }
        });
        kliksignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kliksigninActionPerformed(evt);
            }
        });
        kliksignin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kliksigninKeyPressed(evt);
            }
        });

        lupapassword.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lupapassword.setText("Lupa Password?");
        lupapassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupapasswordMouseClicked(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jCheckBox1.setText("Selalu ingat saya");
        jCheckBox1.setContentAreaFilled(false);

        kliksignin1.setBackground(new java.awt.Color(0, 102, 0));
        kliksignin1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        kliksignin1.setForeground(new java.awt.Color(255, 255, 255));
        kliksignin1.setText("Masuk Sebagai Petani");
        kliksignin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kliksignin1MousePressed(evt);
            }
        });
        kliksignin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kliksignin1ActionPerformed(evt);
            }
        });
        kliksignin1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kliksignin1KeyPressed(evt);
            }
        });

        lupapassword1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lupapassword1.setText("Atau");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(signin))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(password)
                                .addComponent(username)
                                .addComponent(isiusername)
                                .addComponent(kliksignin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(isipassword, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kliksignin1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(lupapassword)
                                .addGap(56, 56, 56))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lupapassword1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(signin)
                .addGap(23, 23, 23)
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isiusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isipassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lupapassword)
                .addGap(14, 14, 14)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kliksignin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lupapassword1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kliksignin1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        si1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        si1.setForeground(new java.awt.Color(255, 255, 255));
        si1.setText("Sistem Informasi ");

        si2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        si2.setForeground(new java.awt.Color(255, 255, 255));
        si2.setText("Harga Hasil Pertanian");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selamatdatang)
                    .addComponent(si2)
                    .addComponent(si1)
                    .addComponent(label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(selamatdatang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(si1)
                .addGap(4, 4, 4)
                .addComponent(si2)
                .addGap(18, 18, 18)
                .addComponent(label1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jDesktopPane1.setLayer(kGradientPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void isiusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiusernameActionPerformed

    private void isiusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiusernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_isiusernameKeyTyped

    private void kliksigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kliksigninActionPerformed
        // TODO add your handling code here:
        ctrllgn.cekakun();
        if (ctrllgn.cekakun() == "pusat") {
            this.setVisible(false);
            new HomeAdmin().setVisible(true);
        }else if (ctrllgn.cekakun() == "daerah") {
            this.setVisible(false);
            new HomeAdminDaerah().setVisible(true);
        }else {
            JOptionPane.showMessageDialog(null,"Maaf Username atau Password Anda Salah");
            isiusername.setText("");
            isipassword.setText("");
        }
    }//GEN-LAST:event_kliksigninActionPerformed

    private void kliksignin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kliksignin1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HomeUser().setVisible(true);
    }//GEN-LAST:event_kliksignin1ActionPerformed

    private void lupapasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupapasswordMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Silahkan Hubungi Admin");
    }//GEN-LAST:event_lupapasswordMouseClicked

    private void kliksigninKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kliksigninKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_kliksigninKeyPressed

    private void kliksignin1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kliksignin1KeyPressed
        // TODO add your handling code here:
        this.setVisible(false);
        new HomeUser().setVisible(true);
    }//GEN-LAST:event_kliksignin1KeyPressed

    private void kliksigninMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kliksigninMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_kliksigninMousePressed

    private void kliksignin1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kliksignin1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_kliksignin1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField isipassword;
    private javax.swing.JTextField isiusername;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JButton kliksignin;
    private javax.swing.JButton kliksignin1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lupapassword;
    private javax.swing.JLabel lupapassword1;
    private javax.swing.JLabel password;
    private javax.swing.JLabel selamatdatang;
    private javax.swing.JLabel si1;
    private javax.swing.JLabel si2;
    private javax.swing.JLabel signin;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
